name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.1
      - run: pip install cpplint
      - run: cpplint --recursive $( find src -name \*.cpp -or -name \*.ino | grep -vE \include )